name: C++ Linter

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Build Compilation Database
        run: platformio run -e esp32dev --target compiledb
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          tidy-checks: ''
          database: compile_commands.json
          files-changed-only: true
          no-lgtm: false
          step-summary: true
          file-annotations: true
          tidy-review: false
          format-review: true
          thread-comments: 'update'
