name: Pull Request Message Validation
on: pull_request

jobs:
  prlint:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Pull Request
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
