# WORK IN PROGRESS
name: Make a new release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true
      release_name:
        description: 'Release name'
        required: true
      release_body:
        description: 'Release body'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
